import React from "react";
import Header from "../../components/Header";
import Head from "next/head";
import Footer from "../../components/Footer";
const Inquiry = () => {

  return (
    <React.Fragment>
      <Head>
        <title>Inquiry</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./images/half circle.svg" />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.7.1/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
          crossOrigin="anonymous"
        ></link>
       

      </Head>
      <Header />
      <section>
        <div className="container px-4 py-2 py-5">
          <div className="row align-items-center g-lg-5 py-5 ">
            <div className="col-lg-12  position-relative">
              <form className="border rounded-3 bg-light pt-5 pb-5 adjust w-75 responsive-form">
                <div className="">
                  <p className="mb-1">Get In Touch</p>
                  <h2 className="fw-bold pb-3 display-5">Start a Conversation</h2>
                </div>
                <div className="row">
                    <div className="col-6">
                <div className="form-floating mb-3">
                  <input
                    type="text"
                    className="form-control"
                    id="floatingInput"
                    placeholder="name@example.com"
                  />
                  <label htmlFor="floatingInput">Name</label>
                </div>
                </div>
                <div className="col-6">
                <div className="form-floating mb-3 adust">
                  <input
                    type="email"
                    className="form-control"
                    id="floatingInput"
                    placeholder="Email"
                  />
                  <label htmlFor="floatingPassword">Email</label>
                </div>
                </div> 
                <div className="col-6">
                <div className="form-floating mb-3 adust">
                  <input
                    type="Company name"
                    className="form-control"
                    id="floatingInput"
                    placeholder="Company name"
                  />
                  <label htmlFor="floatingPassword">Company name</label>
                </div>
                </div>
                <div className="col-6">
                <div className="form-floating mb-3 adust">
                  <input
                    type="Mobile Number"
                    className="form-control"
                    id="floatingPassword"
                    placeholder="Mobile Number"
                  />
                  <label htmlFor="floatingPassword">Mobile Number</label>
                </div>
                </div>
                <div className="col-12">
                <div className="mb-4 adust ">
               <textarea id="message" cols="30" rows="7" placeholder="Message" className="form-control form-floating"></textarea>
                </div>
                </div>
                <div className="col-12">
                <button
                  className="btn btn-lg btn-primary py-3 w-25"
                  type="submit"
                >
                  Get Beta Access
                </button>
                </div>
                </div>
              </form>
              <div className="form-secondimg h-100" >
                <img src="/images/Group 1.svg" alt="Group Image" className="img-fluid h-100"/>
              </div>
            </div>
          </div>
        </div>
      </section>

      

      <Footer />
    </React.Fragment>
  );
};

export default Inquiry;
