import Head from 'next/head'
import Header from '../components/Header'
import Footer from '../components/Footer'
export default function Home() {
  return (
    <>
      < Head >
        <title>Omega</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./images/half circle.svg" />
        
        
      </Head >
      <Header />
      <section>
        <div className="container px-4 py-2 py-5">
          <div className="row align-items-center g-lg-5 py-5">
            <div className="col-md-6  text-center text-lg-start">
              <h1 className="display-4 fw-bold lh-1 mb-3 text-white titlepart">
                Build your next landing page in 5 minutes!
              </h1>
              <p className="col-lg-10 text-white-secondary">
                Create custom landing pages with Omega that convert more visitors
                than any website. With lots of unique blocks, you can easily build a
                page without coding.
              </p>
            </div>
            <div className="mx-auto col-md-6  position-relative">
              <div className="bg-secondimg">
                <img src="/images/Group 1.svg" alt="Group Image" />
              </div>
              <form className="border rounded-3 bg-light mw-380 mx-auto pt-5 pb-5 adjust">
                <div className="form-floating mb-3">
                  <input
                    type="email"
                    className="form-control"
                    id="floatingInput"
                    placeholder="name@example.com"
                  />
                  <label htmlFor="floatingInput">Email address</label>
                </div>
                <div className="form-floating mb-3 adust">
                  <input
                    type="Company name"
                    className="form-control"
                    id="floatingPassword"
                    placeholder="Company name"
                  />
                  <label htmlFor="floatingPassword">Company name</label>
                </div>
                <select
                  className="form-select form-select-lg mb-3"
                  aria-label=".form-select-lg example"
                  defaultValue=""
                >
                  <option value={0} >Company size</option>
                  <option value={1}>One</option>
                  <option value={2}>Two</option>
                  <option value={3}>Three</option>
                </select>
                <select
                  className="form-select form-select-lg mb-3"
                  aria-label=".form-select-lg example"
                  defaultValue=""
                >
                  <option value={0} >Yearly budget</option>
                  <option value={1}>20 lakh</option>
                  <option value={2}>50 lakh</option>
                  <option value={3}>1 Crore</option>
                </select>
                <button className="w-100 btn btn-lg btn-primary py-3" type="submit">
                  Get Beta Access
                </button>
              </form>
            </div>
          </div>
        </div>
      </section>
      <section className="position-relative">
        <div className="bg-imagehalf">
          <img src="/images/half circle.svg" alt="cicrle-image" />
        </div>
        <div className="container px-4 py-5 text-center position-relative">
          <div className="row align-items-center g-lg-5 py-5 padd">
            <div className="col-md-12 text-center text-lg-start ">
              <h1 className="display-4 fw-bold lh-1 mb-3 text-center text-white titlesection">
                Why Omega would <br />
                be your best fit?
              </h1>
              <p className="text-center text-white-secondary custom">
                Watch this 1 min video to learn about Omega.
              </p>
            </div>
          </div>
        </div>
        <div className="container px-4">
          <div className="col-md-12">
            <div className="bg-imageretange">
              <img src="/images/computer.png" alt="computer" className="img-fluid" layout='fill' />
            </div>
          </div>
        </div>
      </section>
      <section>
        <div className="container px-4">
          <div className="row g-4 py-5 row-cols-1 row-cols-lg-3">
            <div className="feature col text-center">
              <div className="feature-icon ">
                <img src="./images/Icon.png" alt="Icon" className="img-fluid" />
              </div>
              <h2 className="text-white">Fully Responsive</h2>
              <p className="text-white">
                With lots of unique blocks, you can easily build a page without
                coding.
              </p>
            </div>
            <div className="feature col text-center">
              <div className="feature-icon">
                <img src="./images/Icon (1).png" alt="Icon-1" />
              </div>
              <h2 className="text-white">Multiple Layouts</h2>
              <p className="text-white">
                With lots of unique blocks, you can easily build a page without
                coding.
              </p>
            </div>
            <div className="feature col2 text-center">
              <div className="feature-icon">
                <img src="./images/Icon (2).png" alt="Icon-2" />
              </div>
              <h2 className="text-white">Faster Loading</h2>
              <p className="text-white">
                With lots of unique blocks, you can easily build a page without
                coding.
              </p>
            </div>
          </div>
        </div>
      </section>
      <section>
        <div className="container px-4">
          <div className="row g-4 py-md-5 row-cols-1 row-cols-lg-3">
            <div className="feature col text-center">
              <div className="feature-icon">
                <img src="./images/Icon (3).png" alt="Icon-3" />
              </div>
              <h2 className="text-white">Super Support</h2>
              <p className="text-white">
                With lots of unique blocks, you can easily build a page without
                coding.
              </p>
            </div>
            <div className="feature col text-center">
              <div className="feature-icon">
                <img src="./images/Icon (4).png" alt="Icon-4" />
              </div>
              <h2 className="text-white">Rich Documentation</h2>
              <p className="text-white">
                With lots of unique blocks, you can easily build a page without
                coding.
              </p>
            </div>
            <div className="feature col2 text-center">
              <div className="feature-icon">
                <img src="./images/Icon (5).png" alt="Icon-5" />
              </div>
              <h2 className="text-white">Lifetime Updates</h2>
              <p className="text-white">
                With lots of unique blocks, you can easily build a page without
                coding.
              </p>
            </div>
          </div>
        </div>
      </section>
      <div className="black border my-5 compress" />
      <section>
        <div className="container px-4 py-5">
          <div className="row align-items-center g-lg-5 py-5">
            <div className="mx-auto col-md-6 " style={{ position: "relative" }}>
              <div className="bg-image ">
                <img src="./images/Oval round1.svg" alt="oval-round-1" className="img-fluid" />
              </div>
              <div className="bg-secondimg oval">
                <img src="./images/Oval round.svg" alt="oval-round" className="img-fluid" />
              </div>
            </div>
            <div className="col-md-6 text-lg-start">
              <button type="button" className="btn btn-primary me-2 rounded-2 mb-5">
                New Feature Added!
              </button>
              <h1 className="display-4 fw-bold lh-1 mb-3 text-white secondary titlesection">
                Drag and drop every elements.
              </h1>
              <p className="col-lg-10 text-white-secondary custom">
                Create custom landing pages with Omega that converts more visitors
                than any website. With lots of unique blocks, you can easily build a
                page without coding.
              </p>
            </div>
          </div>
        </div>
      </section>
      <div className="black border compress" />
      <section>
        <div className="backend">
          <div className="container px-4 py-5 text-center position-relative">
            <div className="row align-items-center g-lg-5 py-5 padd">
              <div className="col-md-12 text-lg-start">
                <h1 className="display-4 fw-bold lh-1 mb-3 text-center text-white titlesection">
                  Everything is easy
                </h1>
                <p className="text-center text-white-secondary custom">
                  Create custom landing pages with Omega that converts more visitors
                  <br /> than any website. With lots of unique blocks, you can
                  easily build a<br />
                  page without coding.
                </p>
              </div>
              <div className="col-md-4 mb-4 mb-md-0 coltext-center text-lg-start titlesection">
                <div className="bgm-image">
                  <img src="./images/pcimage.png" alt="pc-image" className="w-100" />
                </div>
              </div>
              <div className="col-md-8 text-center text-lg-start titlesection">
                <div className="bgm-secondimg move">
                  <img src="./images/pcimage1.png" alt="pc-image-1" className="w-100" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      {/* <div class="black border"></div> */}
      <section>
        <div className="container px-4 py-5">
          <div className="row align-items-center g-lg-5 py-lg-5">
            <div className="col-md-6  text-center text-lg-start">
              <h1 className="display-4 fw-bold lh-1 mb-3 text-white secondary titlesection">
                50k+ users are using this landing page.
              </h1>
              <p className=" col-lg-10 text-white-secondary newtexts">
                Create custom landing pages with Omega that converts more visitors
                than any website. With lots of unique blocks, you can easily build a
                page without coding.
              </p>
              <div className="col-md-3 buttons text-lg-end buton mobilecenter text-center">
                <button type="button" className="btn btn-primary me-2 rounded-2">
                  Get Beta access
                </button>
              </div>
            </div>
            <div className="mx-auto col-md-6" style={{ position: "relative" }}>
              <div className="bg-image bg-image pt-5 pt-lg-0">
                <img src="./images/Ovaldouble.svg" alt="oval-double" className="img-fluid" />
              </div>
            </div>
          </div>
        </div>
      </section>
      <div className="black border compress" >
        <section>
          <div className="container px-4 py-5 text-center position-relative">
            <div className="row align-items-center g-lg-5 py-lg-5 padd">
              <div className="col-md-12 text-center text-lg-start">
                <h1 className="display-4 fw-bold lh-1 mb-3 text-center text-white newtext titlesection">
                  Frequently Asked Question
                </h1>
                <p className="text-center text-white-secondary newtext1">
                  Create custom landing pages with Omega that converts.
                </p>
              </div>
            </div>
          </div>
          <section>
            <div className="container px-4 py-5">
              <div className="row align-items-center g-lg-5 py-lg-5">
                <div className="col-md-6 col-md-6 text-center text-lg-start">
                  <div >
                    <h3 className="text-white">What’s gonna be your question?</h3>
                    <p className="text-white sizefont">
                      Create custom landing pages with Omega that converts more
                      visitors than any website. With lots of unique blocks, you can
                      easily build a page without any design or custom coding.
                    </p>
                  </div>
                  <div >
                    <h3 className="text-white">What’s gonna be your question?</h3>
                    <p className="text-white sizefont">
                      Create custom landing pages with Omega that converts more
                      visitors than any website. With lots of unique blocks, you can
                      easily build a page without any design or custom coding.
                    </p>
                  </div>
                  <div >
                    <h3 className="text-white">What’s gonna be your question?</h3>
                    <p className="text-white sizefont">
                      Create custom landing pages with Omega that converts more
                      visitors than any website. With lots of unique blocks, you can
                      easily build a page without any design or custom coding.
                    </p>
                  </div>
                </div>
                <div className="col-md-6 col-md-6 text-center text-lg-start">
                  <div >
                    <h3 className="text-white">What’s gonna be your question?</h3>
                    <p className="text-white sizefont">
                      Create custom landing pages with Omega that converts more
                      visitors than any website. With lots of unique blocks, you can
                      easily build a page without any design or custom coding.
                    </p>
                  </div>
                  <div >
                    <h3 className="text-white">What’s gonna be your question?</h3>
                    <p className="text-white sizefont">
                      Create custom landing pages with Omega that converts more
                      visitors than any website. With lots of unique blocks, you can
                      easily build a page without any design or custom coding.
                    </p>
                  </div>
                  <div >
                    <h3 className="text-white">What’s gonna be your question?</h3>
                    <p className="text-white sizefont">
                      Create custom landing pages with Omega that converts more
                      visitors than any website. With lots of unique blocks, you can
                      easily build a page without any design or custom coding.
                    </p>
                  </div>
                </div>
                <div className="col-md-12 text-center text-lg-start">
                  <h6 className="text-center text-white">
                    Didn’t find your answer?{" "}
                    <span className="changer">Contact us here</span>
                  </h6>
                </div>
              </div>
            </div>
          </section>
          {/* <div class="black border"></div> */}
          <section>
            <div className="backend1 position-relative ">
              <div className="bg-image demo">
                <img src="./images/two half.svg" alt="two-half" />
              </div>
              <div className="container px-4 py-5">
                <div className="row align-items-center g-lg-5 py-5 ">
                  <div className="col-md-6 text-center text-lg-start">
                    <h1 className="display-4 fw-bold lh-1 mb-3 text-white finish titlesection">
                      Save tons of time.
                      <br />
                      Get new landing page.
                    </h1>
                  </div>
                  <div className="mx-auto col-md-6 mb-4 bg-picture">
                    <div className="buttons text-lg-end buton">
                      <button
                        type="button"
                        className="btn btn-primary  align-items-center rounded-2"
                      >
                        Get Beta access
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>

        </section>
      </div>
      <Footer />
    </ >
  )
}
