import React, { useEffect, useState } from "react";
import Header from "./../components/Header";
import Head from "next/head";
import Link from "next/link";
import Footer from "./../components/Footer";
import SliderCarousel from "./../components/Slider";
import Masonry, { ResponsiveMasonry } from "react-responsive-masonry";
import Data from "./about/data.json";
import OurServices from "./../components/OurServices";
import HubspotForm from "react-hubspot-form";
import AOS from "aos";
import "aos/dist/aos.css";
const HireExpert = ({ data }) => {
  const [tab, setTab] = useState(0);
  useEffect(() => {
    AOS.init();
  }, []);
console.log(data)
  return (
    <div>
      <Head>
        <title>Hire Expert</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./images/half circle.svg" />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.7.1/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
          crossOrigin="anonymous"
        ></link>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />

        {/* <script
          type="text/javascript"
          id="hs-script-loader"
          async
          defer
          src="//js.hs-scripts.com/21780151.js"
        ></script> */}

        <script
          type="text/javascript"
          id="hs-script-loader"
          async
          defer
          src="//js.hs-scripts.com/21780151.js"
        ></script>
      </Head>
      <Header />

      <div className="position-relative">
        <div className="bg-imagehalf"></div>

        <section>
          <div className="container px-4 py-2 py-5">
            <div className="row g-lg-5 py-5">
              <div 
                className="col-md-6 "
                data-aos="fade-right"
                data-aos-offset="200"
                data-aos-easing="ease-in-sine"
                data-aos-duration="900" 
                
              >
                <div dangerouslySetInnerHTML={{ __html: data?.heroPartTitle }}>
                
                </div>
               
                

                {/* <h1 className="fw-bold mb-3 text-white titlepart">
                Programming With No Delays
                </h1>

                <p className="mb-3 text-white guranteeText"> 
                We guarantee you'll be happy after 30 days or we won't invoice you
                </p>
                <ul className="text-white list-inline p-0 mb-5">
                  <li className="lh-lg">
                    <i
                      className="fa fa-check-square-o me-1"
                      aria-hidden="true"
                    ></i>
                    Customer Focused Development
                  </li>
                  <li className="lh-lg">
                    <i
                      className="fa fa-check-square-o me-1"
                      aria-hidden="true"
                    ></i>
                    Industry Unique Performance Guarantee
                  </li>
                  <li className="lh-lg">
                    <i
                      className="fa fa-check-square-o me-1"
                      aria-hidden="true"
                    ></i>
                    Hundreds of developers, designers and project managers at
                    your service
                  </li>
                </ul> */}
                <Link href="/inquiry">
                  <a className="btn-primary p-3 text-decoration-none px-5">
                    Get Started
                  </a>
                </Link>
              </div>
              <div className="mx-auto col-md-6  position-relative R-Top">
                <div className="bg-secondimg">
                  <img src={data?.formBackroundImage.mediaItemUrl} alt="Group Image" />
                </div>
                <form
                  className="border rounded-3 bg-light mw-380 mx-auto pt-5 pb-1"
                  data-aos="fade-left"
                  data-aos-offset="200"
                  data-aos-easing="ease-in-sine"
                  data-aos-duration="900"
                  formId="b6a4f140-c6a0-415c-a7f2-77c40c706e31"
                >
                  <div className="hubspot-container">
                    <HubspotForm
                      portalId="21780151"
                      formId="b6a4f140-c6a0-415c-a7f2-77c40c706e31"
                      onSubmit={() => console.log("Submit!")}
                      onReady={(form) => console.log("Form ready!")}
                      loading={
                        <div>
                          <div className="load1"></div>
                        </div>
                      }
                    />
                  </div>
                </form>
              </div>
            </div>
          </div>
        </section>

        <section className="position-relative">
          <div className="container px-4 py-5 text-center position-relative">
            <div className="row align-items-center g-lg-5 py-5 padd">
              <div className="col-md-12 text-center text-lg-start ">
                <h2 className="secondary-title fw-bold mb-3 text-center text-white titlesection">
                  {data?.masonryImagesTitle}
                </h2>
                <p className="text-center text-white-secondary custom">
                {data?.masonryParagraphText}
                </p>
              </div>
            </div>
          </div>

          <div className="animation-card">
            <div className="container px-4">
              <div className="col-md-12">
                <div className="bg-imageretange">
                  <div className="g-4 py-5">
                    <ResponsiveMasonry
                      columnsCountBreakPoints={{ 550: 4, 750: 4, 900: 4 }}
                    >
                      <Masonry columnsCount={4} gutter="10px">
                        {data?.masonryImages?.map((item, i) => {
                          const classes = i % 2 !== 0 ? "cardItems" : "";
                          return (
                            <div key={i} className={classes}>
                              <img
                                src={item.cardMasonryImage.mediaItemUrl}
                                key={i}
                                alt="Icon"
                                style={{ width: "100%", display: "block" }}
                              />
                            </div>
                          );
                        })}
                      </Masonry>
                    </ResponsiveMasonry>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="services-section">
          <div className="container">
            <div className="sec-title light centered">
              <h2 className="text-white text-center">{data?.serviceBlockStartTitle}</h2>
              <p className="text-white text-center pb-5">
              {data?.serviceBlockStartParagraph}
              </p>
            </div>
            <div
              className="row"
              data-aos="flip-right"
              data-aos-offset="200"
              data-aos-easing="ease-in-sine"
              data-aos-duration="900"
            >
              {data?.serviceBlock?.map((item,i)=><div className="services-block col-lg-4 col-md-6 col-sm-12" key={i}>
                <div className="inner-box-content">
                  <div className="hover-effect"></div>
                  <div className="count"> {i<= 9 && '0' }{i + 1}</div>
                  <h3 className="text-white text-uppercase">{item.serviceTitle}</h3>
                  <div className="icon-box">
                    <img src={item.iconBox.mediaItemUrl} />
                  </div>
                  <div className="text-white">
                    <p>{item.serviceExplanText}</p>
                  </div>
                </div>
              </div>
)

              }

              
              {/* <div className="services-block col-lg-4 col-md-6 col-sm-12">
                <div className="inner-box-content">
                  <div className="hover-effect"></div>
                  <div className="count">02</div>
                  <h3 className="text-white text-uppercase">Web design</h3>
                  <div className="icon-box">
                    <img src="/images/web-designs02.png" />
                  </div>
                  <div className="text-white">
                  <p>Create mission-critical workflows with enterprise-grade web
                    applications.</p>
                  </div>
                </div>
              </div>

              <div className="services-block col-lg-4 col-md-6 col-sm-12">
                <div className="inner-box-content">
                  <div className="hover-effect"></div>
                  <div className="count">03</div>
                  <h3 className="text-white text-uppercase">
                    digital marketing
                  </h3>
                  <div className="icon-box">
                    <img src="/images/bullhorn03.png" />
                  </div>
                  <div className="text-white">
                  <p>Extend your development with top programmers on your terms
                    and with assured outcomes.</p>
                  </div>
                </div>
              </div>

              <div className="services-block col-lg-4 col-md-6 col-sm-12">
                <div className="inner-box-content">
                  <div className="hover-effect"></div>
                  <div className="count">04</div>
                  <h3 className="text-white">CUSTOM SOFTWARE DEVELOPMENT</h3>
                  <div className="icon-box">
                    <img src="/images/setting.png" />
                  </div>
                  <div className="text-white">
                  <p>Build custom applications to solve your specific business
                    difficulties.</p>
                  </div>
                </div>
              </div>

              <div className="services-block col-lg-4 col-md-6 col-sm-12">
                <div className="inner-box-content">
                  <div className="hover-effect"></div>
                  <div className="count">05</div>
                  <h3 className="text-white">ENTERPRISE SOFTWARE SOLUTIONS</h3>
                  <div className="icon-box">
                    <img src="/images/software.png" />
                  </div>
                  <div className="text-white">
                  <p>Working with our product specialists and utilising the best
                    testing services, you can shape and confirm your vision.</p>
                  </div>
                </div>
              </div>

              <div className="services-block col-lg-4 col-md-6 col-sm-12">
                <div className="inner-box-content">
                  <div className="hover-effect"></div>
                  <div className="count">06</div>
                  <h3 className="text-white">SOFTWARE TESTING SERVICES</h3>
                  <div className="icon-box">
                    <img src="/images/analysis.png" />
                  </div>
                  <div className="text-white">
                  <p>With our rigorous QA procedures, you can confidently release
                    software faster.</p>
                  </div>
                </div>
              </div> */}
            </div>
          </div>
        </section>
        <section>
          <div className="BgBlue py-5">
            <div className="container px-4">
              <h2 className="secondary-title fw-bold mb-3 text-white secondary text-center pt-5 titlesection">
              {data?.tabLogoMainTitle}
              </h2>
              <p className="text-white text-center">
              {data?.tabLogoMainParagraph}
              </p>
              <div>
                <div className="tabs pt-5">
                  <input
                    type="radio"
                    name="tabs"
                    id="tabone"
                    defaultChecked={tab === 0}
                    onClick={() => setTab(0)}
                  />
                  <label htmlFor="tabone">Frontend </label>

                  <div className="tab">
                    <div className="g-4 py-5">
                      <ResponsiveMasonry
                        columnsCountBreakPoints={{ 550: 6, 750: 4, 900: 6 }}
                      >
                        <Masonry columnsCount={6} gutter="10px">
                        {data?.tabLogoPhoto?.map((item, i) =>  (
                            <div key={i}>
                              <img
                                src={item.tabImageLogos.mediaItemUrl}      
                                key={i}
                                alt="Icon"
                                style={{ width: "190px", display: "block" }}
                              />
                            </div>
                          ))}
                        </Masonry>
                      </ResponsiveMasonry>
                    </div>
                  </div>

                  <input
                    type="radio"
                    name="tabs"
                    id="tabtwo"
                    defaultChecked={tab === 1}
                    onClick={() => setTab(1)}
                  />
                  <label htmlFor="tabtwo">Backend</label>
                  <div className="tab">
                    <div className="g-4 py-5">
                      <ResponsiveMasonry
                        columnsCountBreakPoints={{ 550: 6, 750: 4, 900: 6 }}
                      >
                        <Masonry columnsCount={6} gutter="10px">
                        {data?.tabLogoBankend?.map((item, i) => (
                            <div key={i}>
                              <img
                                src={item.tabBackendImage.mediaItemUrl}
                                key={i}
                                alt="Icon"
                                style={{ width: "190px", display: "block" }}
                              />
                            </div>
                          ))}
                        </Masonry>
                      </ResponsiveMasonry>
                    </div>
                  </div>

                  <input
                    type="radio"
                    name="tabs"
                    id="tabthree"
                    defaultChecked={tab === 2}
                    onClick={() => setTab(2)}
                  />
                  <label htmlFor="tabthree">Database</label>
                  <div className="tab">
                    <div className="g-4 py-5">
                      <ResponsiveMasonry
                        columnsCountBreakPoints={{ 550: 6, 750: 4, 900: 6 }}
                      >
                        <Masonry columnsCount={6} gutter="10px">
                        {data?.tabLogoDatabase?.map((item, i) => (
                            <div key={i}>
                              <img
                                src={item.tabDatabaseImages.mediaItemUrl}
                                key={i}
                                alt="Icon"
                                style={{ width: "190px", display: "block" }}
                              />
                            </div>
                          ))}
                        </Masonry>
                      </ResponsiveMasonry>
                    </div>
                  </div>

                  <input
                    type="radio"
                    name="tabs"
                    id="tabfour"
                    defaultChecked={tab === 3}
                    onClick={() => setTab(3)}
                  />
                  <label htmlFor="tabfour">CMS</label>
                  <div className="tab">
                    <div className="g-4 py-5">
                      <ResponsiveMasonry
                        columnsCountBreakPoints={{ 550: 6, 750: 4, 900: 6 }}
                      >
                        <Masonry columnsCount={6} gutter="10px">
                        {data?.tabLogoCms?.map((item, i) => (
                            <div key={i}>
                              <img
                                src={item.tabCmsImages.mediaItemUrl}
                                key={i}
                                alt="Icon"
                                style={{ width: "190px", display: "block" }}
                              />
                            </div>
                          ))}
                        </Masonry>
                      </ResponsiveMasonry>
                    </div>
                  </div>

                  <input
                    type="radio"
                    name="tabs"
                    id="tabfive"
                    defaultChecked={tab === 4}
                    onClick={() => setTab(4)}
                  />
                  <label htmlFor="tabfive">Cloud</label>
                  <div className="tab">
                    <div className="g-4 py-5">
                      <ResponsiveMasonry
                        columnsCountBreakPoints={{ 550: 6, 750: 4, 900: 6 }}
                      >
                        <Masonry columnsCount={6} gutter="10px">
                        {data?.tabLogoCloud?.map((item, i) => (
                            <div key={i}>
                              <img
                                src={item.tabCloudImages.mediaItemUrl}
                                key={i}
                                alt="Icon"
                                style={{ width: "190px", display: "block" }}
                              />
                            </div>
                          ))}
                        </Masonry>
                      </ResponsiveMasonry>
                    </div>
                  </div>

                  <input
                    type="radio"
                    name="tabs"
                    id="tabsix"
                    defaultChecked={tab === 5}
                    onClick={() => setTab(5)}
                  />
                  <label htmlFor="tabsix">Testing</label>
                  <div className="tab">
                    <div className="g-4 py-5">
                      <ResponsiveMasonry
                        columnsCountBreakPoints={{ 550: 6, 750: 4, 900: 6 }}
                      >
                        <Masonry columnsCount={6} gutter="10px">
                        {data?.tabLogoTesting?.map((item, i) => (
                            <div key={i}>
                              <img
                                src={item.tabTestingImages.mediaItemUrl}
                                key={i}
                                alt="Icon"
                                style={{ width: "190px", display: "block" }}
                              />
                            </div>
                          ))}
                        </Masonry>
                      </ResponsiveMasonry>
                    </div>
                  </div>

                  <input
                    type="radio"
                    name="tabs"
                    id="tabseven"
                    defaultChecked={tab === 6}
                    onClick={() => setTab(6)}
                  />
                  <label htmlFor="tabseven">Mobile App</label>
                  <div className="tab">
                    <div className="g-4 py-5">
                      <ResponsiveMasonry
                        columnsCountBreakPoints={{ 550: 6, 750: 4, 900: 6 }}
                      >
                        <Masonry columnsCount={6} gutter="10px">
                        {data?.tabLogoApp?.map((item, i) => (
                            <div key={i}>
                              <img
                                src={item.tabAppImages.mediaItemUrl}
                                key={i}
                                alt="Icon"
                                style={{ width: "190px", display: "block" }}
                              />
                            </div>
                          ))}
                        </Masonry>
                      </ResponsiveMasonry>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section>
          <div className="container px-4 py-5">
            <div className="row align-items-center g-lg-5 py-5">
              <div className="col-md-7 text-lg-start">
                <h2 className="secondary-title fw-bold lh-1 mb-3 text-white secondary titlesection">
                {data?.whoAreTitle}
                </h2>
                <p className="mb-4 text-white-secondary custom">
                {data?.whoAreParagraph}
                </p>
                <a href={data?.whoAreButton} className="btn btn-primary me-2 rounded-2 py-2">Dedicated Team</a>
              </div>
              <div className="mx-auto col-md-5 " dangerouslySetInnerHTML={{ __html: data?.coexperienceListText }}>
              
                {/* <ul className="Coexperience list-inline">
                
                  <li>
                    350+
                    <div>Qualified Experts</div>
                  </li>
                  <li>
                    1,000+
                    <div>Projects Delivered</div>
                  </li>
                  <li>
                    150+
                    <div>Satisfied Customers</div>
                  </li>
                  <li>
                    42%
                    <div>YOY Growth</div>
                  </li>
                </ul> */}
              </div>
            </div>
          </div>
        </section>

        <section>
          <div className="companyCards spacers">
            <div className="container">
              <h2 className="secondary-title fw-bold text-center text-white">
              {data?.companyCardsTitleMain}
              </h2>
              <p className="text-white text-opacity-50 text-center mb-5">
              {data?.companyCardsMainPharagraph}
              </p>
              <div
                className="pt-4"
                data-aos="fade-up"
                data-aos-offset="200"
                data-aos-easing="ease-in-sine"
                data-aos-duration="900"
              >
                <div className="row">
                {data?.companyCards?.map((item,i)=><div className="col-lg-4" key={i}>
                    <div className="iconWork d-flex fadeInUp">
                      <div className="me-3" dangerouslySetInnerHTML={{ __html: item.iconWorkFont }}>
                        {/* <i className="fas fa-chalkboard-teacher" >{item.iconWorkFont}</i> */}
                      </div>
                      <div>
                        <h3 className="text-white fw-bold fs-4">{item.iconsWorkTitle}</h3>
                        <p className="text-white text-opacity-50">{item.iconsWorkExplan}</p>
                      </div>
                    </div>
                  </div>
                )}

                  {/* <div className="col-lg-4">
                    <div className="iconWork d-flex fadeInUp">
                      <div className="me-3">
                        <i className="fas fa-paper-plane"></i>
                      </div>
                      <div>
                        <h3 className="text-white fw-bold fs-4">WE DEVELOP</h3>
                        <p className="text-white text-opacity-50">
                          We see beyond the insights and take you to the eye
                          stand.
                        </p>
                      </div>
                    </div>
                  </div>
                  <div className="col-lg-4">
                    <div className="iconWork d-flex fadeInUp">
                      <div className="me-3">
                        <i className="fas fa-paste"></i>
                      </div>
                      <div>
                        <h3 className="text-white fw-bold fs-4">WE DELIVER</h3>
                        <p className="text-white text-opacity-50">
                          As a multifaceted digital marketing agency, we craft
                          beautiful solutions that outdo business goals and
                          garner recognition.
                        </p>
                      </div>
                    </div>
                  </div> */}
                </div>
              </div>
            </div>
          </div>
        </section>


        {/* <section>
        <div className="backend">
          <div className="container px-4 py-5 text-center position-relative">
            <div className="row align-items-center g-lg-5 py-5 padd">
              <div className="col-md-12 text-lg-start">
              <h2 className="text-center text-white pb-2">
              Certifications and Partnerships
            </h2>
              </div>
              <SliderCarousel 
              settings={Data.settings}
              data={Data.imageGallery}
              />
            </div>
          </div>
        </div>
      </section> */}
        {/* <section>
          <div className="videoTestimonials py-5">
              <div className="container">
              <h2 className="text-center text-white py-5">
              Video Testimonials
                </h2>
                  <div className="row">
                      <div className="col-lg-4">
                          <div className="VideoImage">
                          <iframe width="420" height="315" src="https://www.youtube.com/embed/Tn6-PIqc4UM" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen></iframe>
                        </div>
                    </div>
                    <div className="col-lg-4">
                          <div className="VideoImage">
                          <iframe width="420" height="315" src="https://www.youtube.com/embed/Tn6-PIqc4UM" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen></iframe>
                        </div>
                    </div>
                    <div className="col-lg-4">
                          <div className="VideoImage">
                          <iframe width="420" height="315" src="https://www.youtube.com/embed/Tn6-PIqc4UM" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen></iframe>
                        </div>
                    </div>
                      </div>
                  </div>
              </div>
      </section> */}

        <section>
          <div className="ClientsExperiences pb-5">
            <div className="container">
              <div className="py-5">
                <h2 className="secondary-title fw-bold text-center text-white">
                  {data?.clientsExperiencesMainTitle}
                </h2>
                <p className="text-center text-white">
                {data?.clientsExperiencesMainPharagraph}
                </p>
              </div>
              <div className="row">
                {data?.clientsExperiences?.map((item,i)=><div className="col-lg-4" key={i}>
                  <div className="clientsCard bg-white text-center p-4 btn draw-border">
                    <img
                      src={item.clientPhotoLogo.mediaItemUrl}
                      alt="Icon-5"
                      className="img-fluid pb-2"
                    />
                    <p>{item.clientExperiseExplan}</p>
                    <p>{item.clientText}</p>
                    <p className="text-primary">{item.clientTextName}</p>
                  </div>
                </div>
                )}
                {/* <div className="col-lg-4">
                  <div className="clientsCard bg-white text-center p-4 btn draw-border">
                    <img
                      src="./images/wn-logo.png"
                      alt="Icon-5"
                      className="img-fluid pb-2"
                    />
                    <p>
                      The team is performing really well. They are learning fast
                      and work with our team and culture well.
                    </p>
                    <p className="pt-5">‐ Applications Director</p>
                    <p className="text-primary">Western National Insurance</p>
                  </div>
                </div>
                <div className="col-lg-4">
                  <div className="clientsCard bg-white text-center p-4 btn draw-border">
                    <img
                      src="./images/saia-logo.png"
                      alt="Icon-5"
                      className="img-fluid pb-2"
                    />
                    <p>
                      The team at Programmers.io has been fantastic. I was
                      surprised at how fast they learned our system and were
                      producing code…
                    </p>
                    <p className="pt-4">‐ EDI Manager</p>
                    <p className="text-primary">Saia</p>
                  </div>
                </div> */}
              </div>
            </div>
          </div>
        </section>
      </div>

      <Footer />
    </div>
  );
};
// This function gets called at build time on server-side.
// It won't be called on client-side, so you can even do
// direct database queries.
export async function getStaticProps() {
  const res = await fetch("http://localhost/pixel-mutation/graphql", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      query: `
        query HirExpertQuery {
          page(id: "cG9zdDo3") {
            id
            hireField {
              heroPartTitle
              formBackroundImage {
                mediaItemUrl
              }
              masonryImagesTitle
              masonryParagraphText
              masonryImages {
                cardMasonryImage {
                  mediaItemUrl
                }
              }
              serviceBlockStartTitle
              serviceBlockStartParagraph
              serviceBlock {
                serviceTitle
                serviceExplanText
                iconBox {
                  mediaItemUrl
                }
              }
              companyCardsTitleMain
              companyCardsMainPharagraph
              companyCards {
                iconWorkFont
                iconsWorkExplan
                iconsWorkTitle
              }
              clientsExperiencesMainTitle
              clientsExperiencesMainPharagraph
              clientsExperiences {
                clientExperiseExplan
                clientPhotoLogo {
                  mediaItemUrl
                }
                clientText
                clientTextName
              }
              tabLogoMainTitle
              tabLogoMainParagraph
              tabLogoPhoto {
                tabImageLogos {
                  mediaItemUrl
              }
            }
            tabLogoBankend {
              tabBackendImage {
                mediaItemUrl
              }
            }
            tabLogoDatabase {
              tabDatabaseImages {
                mediaItemUrl
              }
            }
            tabLogoCms {
              tabCmsImages {
                mediaItemUrl
              }
            }
            tabLogoCloud {
              tabCloudImages {
                mediaItemUrl
              }
            }
            tabLogoTesting {
              tabTestingImages {
                mediaItemUrl
              }
            }
            tabLogoApp {
              tabAppImages {
                mediaItemUrl
              }
            }
            whoAreTitle
      whoAreParagraph
      whoAreButton {
        url
      }
      coexperienceListText
            }
          }
        }
        `,
    }),
  });

  const json = await res.json();
  return {
    props: {
      data: json.data.page.hireField,
    },
  };
}

export default HireExpert;
